const data = {
  products: [
    {
      name: "Nike",
      slug: "nike-Slim-Shirt",
      Category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countinstock: 10,
      brand: "nike",
      rating: 4.7,
      numReviews: 10,
      description: "high Quality Shirt",
    },
    {
      name: "Adidas",
      slug: "Shoes",
      Category: "Shoes",
      image: "/images/p2.jpg",
      price: 720,
      countinstock: 14,
      brand: "adidas",
      rating: 4.3,
      numReviews: 40,
      description: "high Quality Shoes",
    },
    {
      name: "Reebok",
      slug: "nike-Socks",
      Category: "Socks",
      image: "/images/p3.jpg",
      price: 90,
      countinstock: 70,
      brand: "reebok",
      rating: 3.7,
      numReviews: 180,
      description: "high Quality Socks",
    },
  ],
};
